### ISSUE TITLE
Not able to make WETH swap

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1015]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/945404583604273162

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

The user wanted to swap WETH for USDT

### What did not work?

WETH Balance is showing but the to be received USDT qty isn't calculated. Also not able to click 'Get final quote'

![image](https://user-images.githubusercontent.com/71384922/155026599-393e498b-d200-493c-b70a-4ff648eeb2a1.png)

### Version

Community Edition v0.11.2

### Relevant log output

<details>
```shell
background.js:77588 internal: request payload: {"id":"30","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91216:22
    at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:50)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:16.836Z
background.js:77588 internal: request payload: {"id":"31","target":"tally-provider-bridge","request":{"method":"eth_chainId","params":[]}}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91216:22
    at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:50)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:16.836Z
background.js:77588 internal response: {id: '31', result: '1'}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91222:24
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:16.852Z
background.js:77588 internal response: {id: '30', result: Array(1)}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91222:24
    at async Promise.all (index 0)
    at async Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:11)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:18.220Z
background.js:77588 internal: request payload: {"id":"32","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91216:22
    at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:50)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:18.222Z
background.js:77588 internal response: {id: '32', result: Array(1)}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91222:24
    at async Promise.all (index 0)
    at async Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:11)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:18.223Z
background.js:77588 internal: request payload: {"id":"33","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91216:22
    at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:50)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:18.224Z
background.js:77588 internal response: {id: '33', result: Array(1)}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91222:24
    at async Promise.all (index 0)
    at async Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:11)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:18.225Z
background.js:77588 internal: request payload: {"id":"34","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91216:22
    at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:50)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:18.226Z
background.js:77588 internal response: {id: '34', result: Array(1)}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91222:24
    at async Promise.all (index 0)
    at async Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:11)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:18.230Z
background.js:77588 internal: request payload: {"id":"35","target":"tally-provider-bridge","request":{"method":"eth_chainId","params":[]}}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91216:22
    at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:50)
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:18.230Z
background.js:77588 internal response: {id: '35', result: '1'}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91222:24
background.js:77587  🪵 Tally log @ 2022-02-21T20:18:18.231Z
background.js:77588 internal: request payload: {"id":"36","target":"tally-provider-bridge","request":{"method":"eth_call","params":[{"from":"0xfbdd6ed4469b7d9a65fbf8b7f4160fbbd2ad7aa9","to":"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","data":"0xdd62ed3e000000000000000000000000fbdd6ed4469b7d9a65fbf8b7f4160fbbd2ad7aa9000000000000000000000000def1c0ded9bec7f1a1670819833240f027b25eff"},"latest"]}}
background.js:77596     at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:91216:22
    at chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://ngadognehgpdejcamckkhkokpndpdhgm/background.js:5595:50)
background.js:77022 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ background.js:77022
send @ background.js:76999
send @ background.js:87916
routeSafeRPCRequest @ background.js:91286
(anonymous) @ background.js:91220
(anonymous) @ background.js:5597
emit @ background.js:5595
await in emit (async)
postMessage @ background.js:91176
request @ background.js:91114
(anonymous) @ background.js:90966
send @ background.js:91026
(anonymous) @ background.js:76764
(anonymous) @ background.js:76303
json_rpc_provider_awaiter @ background.js:76285
perform @ background.js:76743
(anonymous) @ background.js:75839
fulfilled @ background.js:74644
Promise.then (async)
step @ background.js:74657
fulfilled @ background.js:74644
Promise.then (async)
step @ background.js:74657
(anonymous) @ background.js:74659
base_provider_awaiter @ background.js:74641
call @ background.js:75833
(anonymous) @ background.js:8979
fulfilled @ background.js:8930
Promise.then (async)
step @ background.js:8943
(anonymous) @ background.js:8945
__awaiter @ background.js:8927
call @ background.js:8976
(anonymous) @ background.js:89582
fulfilled @ background.js:89339
Promise.then (async)
step @ background.js:89352
(anonymous) @ background.js:89354
contracts_lib_esm_awaiter @ background.js:89336
(anonymous) @ background.js:89568
(anonymous) @ background.js:95293
await in (anonymous) (async)
(anonymous) @ background.js:94687
(anonymous) @ background.js:66866
step @ background.js:65746
(anonymous) @ background.js:65690
(anonymous) @ background.js:65808
__async @ background.js:65790
(anonymous) @ background.js:66843
(anonymous) @ background.js:66906
(anonymous) @ background.js:65641
(anonymous) @ background.js:63010
dispatchResponse @ background.js:63569
(anonymous) @ background.js:63127
background.js:77587  ❌ Tally error @ 2022-02-21T20:19:19.734Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
error @ background.js:77614
getBlockPrices @ background.js:82977
background.js:77022 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ background.js:77022
send @ background.js:76999
(anonymous) @ background.js:76764
(anonymous) @ background.js:76303
json_rpc_provider_awaiter @ background.js:76285
perform @ background.js:76743
(anonymous) @ background.js:75617
fulfilled @ background.js:74644
Promise.then (async)
step @ background.js:74657
(anonymous) @ background.js:74659
base_provider_awaiter @ background.js:74641
getGasPrice @ background.js:75615
(anonymous) @ background.js:8887
(anonymous) @ background.js:8826
__awaiter @ background.js:8808
getFeeData @ background.js:8884
getBlockPrices @ background.js:82980
background.js:77022 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ background.js:77022
send @ background.js:76999
(anonymous) @ background.js:76764
(anonymous) @ background.js:76303
json_rpc_provider_awaiter @ background.js:76285
perform @ background.js:76743
(anonymous) @ background.js:75907
(anonymous) @ background.js:74659
base_provider_awaiter @ background.js:74641
base_provider_awaiter.oncePoll @ background.js:75906
check @ background.js:16098
(anonymous) @ background.js:16131
poll @ background.js:16075
(anonymous) @ background.js:75906
fulfilled @ background.js:74644
Promise.then (async)
step @ background.js:74657
fulfilled @ background.js:74644
Promise.then (async)
step @ background.js:74657
fulfilled @ background.js:74644
Promise.then (async)
step @ background.js:74657
(anonymous) @ background.js:74659
base_provider_awaiter @ background.js:74641
_getBlock @ background.js:75887
getBlock @ background.js:75949
getBlockPrices @ background.js:82980
background.js:77022 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ background.js:77022
send @ background.js:76999
(anonymous) @ background.js:76764
(anonymous) @ background.js:76303
json_rpc_provider_awaiter @ background.js:76285
perform @ background.js:76743
(anonymous) @ background.js:75907
(anonymous) @ background.js:74659
base_provider_awaiter @ background.js:74641
base_provider_awaiter.oncePoll @ background.js:75906
check @ background.js:16098
(anonymous) @ background.js:16131
poll @ background.js:16075
(anonymous) @ background.js:75906
fulfilled @ background.js:74644
Promise.then (async)
step @ background.js:74657
fulfilled @ background.js:74644
Promise.then (async)
step @ background.js:74657
fulfilled @ background.js:74644
Promise.then (async)
step @ background.js:74657
(anonymous) @ background.js:74659
base_provider_awaiter @ background.js:74641
_getBlock @ background.js:75887
getBlock @ background.js:75949
(anonymous) @ background.js:8886
(anonymous) @ background.js:8826
__awaiter @ background.js:8808
getFeeData @ background.js:8884
getBlockPrices @ background.js:82980
background.js:77664          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77664
(anonymous) @ background.js:77644
geturl_awaiter @ background.js:77626
getUrl @ background.js:77648
(anonymous) @ background.js:77869
(anonymous) @ background.js:77708
web_lib_esm_awaiter @ background.js:77690
(anonymous) @ background.js:77865
_fetchData @ background.js:77957
lib_esm_fetchJson @ background.js:77997
getBlockPrices @ background.js:82952
getBlockPrices @ background.js:82975
(anonymous) @ background.js:87911
pollBlockPrices @ background.js:87910
handler @ background.js:87716
handleAlarm @ background.js:73981
background.js:77664          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77664
(anonymous) @ background.js:77644
geturl_awaiter @ background.js:77626
getUrl @ background.js:77648
(anonymous) @ background.js:77869
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
(anonymous) @ background.js:77708
web_lib_esm_awaiter @ background.js:77690
(anonymous) @ background.js:77865
_fetchData @ background.js:77957
lib_esm_fetchJson @ background.js:77997
getBlockPrices @ background.js:82952
getBlockPrices @ background.js:82975
(anonymous) @ background.js:87911
pollBlockPrices @ background.js:87910
handler @ background.js:87716
handleAlarm @ background.js:73981
background.js:77664          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77664
(anonymous) @ background.js:77644
geturl_awaiter @ background.js:77626
getUrl @ background.js:77648
(anonymous) @ background.js:77869
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
(anonymous) @ background.js:77708
web_lib_esm_awaiter @ background.js:77690
(anonymous) @ background.js:77865
_fetchData @ background.js:77957
lib_esm_fetchJson @ background.js:77997
getBlockPrices @ background.js:82952
getBlockPrices @ background.js:82975
(anonymous) @ background.js:87911
pollBlockPrices @ background.js:87910
handler @ background.js:87716
handleAlarm @ background.js:73981
background.js:77664          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77664
(anonymous) @ background.js:77644
geturl_awaiter @ background.js:77626
getUrl @ background.js:77648
(anonymous) @ background.js:77869
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
(anonymous) @ background.js:77708
web_lib_esm_awaiter @ background.js:77690
(anonymous) @ background.js:77865
_fetchData @ background.js:77957
lib_esm_fetchJson @ background.js:77997
getBlockPrices @ background.js:82952
getBlockPrices @ background.js:82975
(anonymous) @ background.js:87911
pollBlockPrices @ background.js:87910
handler @ background.js:87716
handleAlarm @ background.js:73981
background.js:77664          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77664
(anonymous) @ background.js:77644
geturl_awaiter @ background.js:77626
getUrl @ background.js:77648
(anonymous) @ background.js:77869
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
(anonymous) @ background.js:77708
web_lib_esm_awaiter @ background.js:77690
(anonymous) @ background.js:77865
_fetchData @ background.js:77957
lib_esm_fetchJson @ background.js:77997
getBlockPrices @ background.js:82952
getBlockPrices @ background.js:82975
(anonymous) @ background.js:87911
pollBlockPrices @ background.js:87910
handler @ background.js:87716
handleAlarm @ background.js:73981
background.js:77664          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77664
(anonymous) @ background.js:77644
geturl_awaiter @ background.js:77626
getUrl @ background.js:77648
(anonymous) @ background.js:77869
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
(anonymous) @ background.js:77708
web_lib_esm_awaiter @ background.js:77690
(anonymous) @ background.js:77865
_fetchData @ background.js:77957
lib_esm_fetchJson @ background.js:77997
getBlockPrices @ background.js:82952
getBlockPrices @ background.js:82975
(anonymous) @ background.js:87911
pollBlockPrices @ background.js:87910
handler @ background.js:87716
handleAlarm @ background.js:73981
background.js:77664          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77664
(anonymous) @ background.js:77644
geturl_awaiter @ background.js:77626
getUrl @ background.js:77648
(anonymous) @ background.js:77869
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
Promise.then (async)
step @ background.js:77706
fulfilled @ background.js:77693
```
</details>

**Comment by Shadowfiend** [comment]
> background.js:77022 WebSocket is already in CLOSING or CLOSED state.

This is interesting. Looks like the Alchemy connection kicked the bucket. Will dig in further and see if this is due to rate limits or something else.

**Comment by Naxsun** [comment]
Had this myself just now as well. Disabling and enabling Tally again fixed it.

Was after a fresh install ± 8 hours ago. Initially the quote and swap function was working properly.

"
WebSocket is already in CLOSING or CLOSED state.
Async thunk failed Error: bad response (status=400, headers={"access-control-allow-credentials":"true","access-control-allow-headers":"DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,0x-api-key","access-control-allow-methods":"GET, PUT, POST, DELETE, PATCH, OPTIONS","access-control-allow-origin":"*","access-control-max-age":"1728000","cache-control":"public, max-age=13, s-maxage=13","content-length":"137","content-
"

**Comment by Shadowfiend** [comment]
Looks like bad connection management, probably causing some widespread issues. I'm working on this right now as a broader part of multi-network stuff.
