### ISSUE TITLE
Assets not displayed in wallet

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1067]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/948293203570864178

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Combining the reports of a couple of users. 

Test the wallet, try out swaps

### What did not work?

User 1: WETH balance not showing up after swap - Swap was succesful
https://discord.com/channels/808358975287722045/888500174685614090/948293203570864178
Version - 0.11.2 as downloaded from the chrome store

![image](https://user-images.githubusercontent.com/71384922/156359348-0c5c3e6a-7b86-4ea5-8484-51aa1611d336.png)

User 2: USDC balance not showing up --> logs below
https://discord.com/channels/808358975287722045/888500174685614090/948340873622618132
Version - 0.11.2 as downloaded from the chrome store

User 3: USDC balance not showing up --> logs below
https://discord.com/channels/808358975287722045/888500174685614090/948341655046602803
Version - 0.11.2 as downloaded from the chrome store

User 4:
https://discord.com/channels/808358975287722045/888500174685614090/948351504849465354

User 5:
https://discord.com/channels/808358975287722045/888500174685614090/948431930637049896

User 6
https://discord.com/channels/808358975287722045/888500174685614090/948441196466958336

### Version

Community Edition v0.11.2

### Relevant log output

```shell
User 2
background.js:77587  🐛 Tally debug @ 2022-03-01T22:04:21.420Z
background.js:77596     at TelemetryService.checkStorageUsage (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:91403:20)
background.js:77587  ❌ Tally error @ 2022-03-01T22:06:21.946Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:09:21.012Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:13:21.045Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:15:21.049Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:17:21.073Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:19:21.092Z
background.js:77587  ❌ Tally error @ 2022-03-01T22:21:21.100Z
background.js:77587  ❌ Tally error @ 2022-03-01T22:27:21.169Z
background.js:77587  ❌ Tally error @ 2022-03-01T22:29:21.188Z
background.js:77587  ❌ Tally error @ 2022-03-01T22:31:21.202Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:33:21.212Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:37:21.252Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:39:21.262Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:41:21.267Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:47:21.326Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:49:15.978Z
background.js:77588 Error getting block prices from BlockNative Error: failed response (requestBody=null, requestMethod="GET", url="https://api.blocknative.com/gasprices/blockprices", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at Logger.throwError (background.js:11671:22)
    at background.js:77951:37
    at Generator.next (<anonymous>)
    at fulfilled (background.js:77693:28)
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:51:21.356Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T22:52:48.009Z
background.js:77588 Error getting block prices from BlockNative Error: failed response (requestBody=null, requestMethod="GET", url="https://api.blocknative.com/gasprices/blockprices", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at Logger.throwError (background.js:11671:22)
    at background.js:77951:37
    at Generator.next (<anonymous>)
    at fulfilled (background.js:77693:28)
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:01:21.420Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:04:21.445Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  🐛 Tally debug @ 2022-03-01T23:04:21.454Z
background.js:77596     at TelemetryService.checkStorageUsage (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:91403:20)
background.js:77587  ❌ Tally error @ 2022-03-01T23:06:21.464Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:08:16.042Z
background.js:77588 Error getting block prices from BlockNative Error: failed response (requestBody=null, requestMethod="GET", url="https://api.blocknative.com/gasprices/blockprices", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at Logger.throwError (background.js:11671:22)
    at background.js:77951:37
    at Generator.next (<anonymous>)
    at fulfilled (background.js:77693:28)
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:10:21.497Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:12:21.519Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:14:21.536Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:18:21.566Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:20:21.584Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:24:21.607Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:26:21.630Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:30:06.307Z
background.js:77588 Error getting block prices from BlockNative Error: failed response (requestBody=null, requestMethod="GET", url="https://api.blocknative.com/gasprices/blockprices", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at Logger.throwError (background.js:11671:22)
    at background.js:77951:37
    at Generator.next (<anonymous>)
    at fulfilled (background.js:77693:28)
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:32:21.683Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:34:21.700Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:36:21.706Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:38:21.711Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:40:21.728Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:46:21.778Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:48:21.784Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:51:45.676Z
background.js:77588 Error getting block prices from BlockNative Error: failed response (requestBody=null, requestMethod="GET", url="https://api.blocknative.com/gasprices/blockprices", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at Logger.throwError (background.js:11671:22)
    at background.js:77951:37
    at Generator.next (<anonymous>)
    at fulfilled (background.js:77693:28)
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:54:21.838Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:56:21.849Z
background.js:77588 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77843:41
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-03-01T23:58:12.989Z
background.js:77588 Error getting block prices from BlockNative Error: failed response (requestBody=null, requestMethod="GET", url="https://api.blocknative.com/gasprices/blockprices", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at Logger.throwError (background.js:11671:22)
    at background.js:77951:37
    at Generator.next (<anonymous>)
    at fulfilled (background.js:77693:28)
genericLogger @ background.js:77588


User 3:

Failed to load resource: the server responded with a status of 500 ()
background.js:77587  ❌ Tally error @ 2022-03-01T22:29:04.319Z
background.js:77588 Async thunk failed Error: bad response (status=500, headers={"access-control-allow-credentials":"true","access-control-allow-headers":"DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,0x-api-key","access-control-allow-methods":"GET, PUT, POST, DELETE, PATCH, OPTIONS","access-control-allow-origin":"*","access-control-max-age":"1728000","cache-control":"public, max-age=13, s-maxage=13","content-length":"25","content-type":"application/json; charset=utf-8","date":"Tue, 01 Mar 2022 22:29:04 GMT","etag":"W/"19-j+Qnwndf1ZQx8GXzsPfd19A9qE0"","strict-transport-security":"max-age=15724800; includeSubDomains","x-powered-by":"Express"}, body="{"reason":"Server Error"}", requestBody=null, requestMethod="GET", url="https://gated.api.0x.org/swap/v1/price?sellToken=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&buyToken=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&gasPrice=53785131229&slippagePercentage=0.01&sellAmount=0&affiliateAddress=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&feeRecipient=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&buyTokenPercentageFee=0.005&takerAddress=0x262Fe2924efC5D6e411d5d69Cd9Ff7ae1a8c852c", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at Logger.throwError (background.js:11671:22)
    at background.js:77912:34
    at Generator.next (<anonymous>)
    at fulfilled (background.js:77693:28)
genericLogger @ background.js:77588
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
DevTools failed to load source map: Could not load content for chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
background.js:77588 Async thunk failed Error: bad response (status=500, headers={"access-control-allow-credentials":"true","access-control-allow-headers":"DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,0x-api-key","access-control-allow-methods":"GET, PUT, POST, DELETE, PATCH, OPTIONS","access-control-allow-origin":"*","access-control-max-age":"1728000","cache-control":"public, max-age=13, s-maxage=13","content-length":"25","content-type":"application/json; charset=utf-8","date":"Tue, 01 Mar 2022 22:31:16 GMT","etag":"W/"19-j+Qnwndf1ZQx8GXzsPfd19A9qE0"","strict-transport-security":"max-age=15724800; includeSubDomains","x-powered-by":"Express"}, body="{"reason":"Server Error"}", requestBody=null, requestMethod="GET", url="https://gated.api.0x.org/swap/v1/price?sellToken=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&buyToken=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&gasPrice=42435643038&slippagePercentage=0.01&sellAmount=0&affiliateAddress=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&feeRecipient=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&buyTokenPercentageFee=0.005&takerAddress=0x262Fe2924efC5D6e411d5d69Cd9Ff7ae1a8c852c", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at Logger.throwError (background.js:11671:22)
    at background.js:77912:34
    at Generator.next (<anonymous>)
    at fulfilled (background.js:77693:28)
```

**Comment by Shadowfiend** [comment]
Do we have any transaction hashes for the swaps that didn't update the balance, by any chance?

**Comment by Naxsun** [comment]
Asked, will add if possible. Meanwhile the user did two wallet re-installs and the ETH is now showing up. He's stuck in swapping now but that could be similar to https://github.com/tallycash/extension/issues/1015

Checking if we can get the logs

**Comment by 0xDaedalus** [comment]
I believe this will be addressed by https://github.com/tallycash/extension/pull/1556

**Comment by SJQuality** [comment]
QA blocked by https://github.com/tallycash/extension/issues/1587
