### ISSUE TITLE
Not connecting to 1inch, although extension says connected

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1072]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect to 1inch exchange via Tally

### What did not work?

Tally extensions says It's connected, 1inch doesn't recognize it as connected. 

Don't know if this is on 1inch or Tally side.

<img width="415" alt="Screenshot 2022-03-03 at 11 12 41" src="https://user-images.githubusercontent.com/71384922/156544013-ec09599e-3af0-4485-b4bb-8ee93d133739.png">
<img width="1370" alt="Screenshot 2022-03-03 at 11 12 28" src="https://user-images.githubusercontent.com/71384922/156544028-8e787af5-d96b-4c86-8736-7191dfa99afd.png">

### Version

Community Edition v0.12.0

### Relevant log output

```shell
background.js:77601 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77856:41
genericLogger @ background.js:77601
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
background.js:77600  🪵 Tally log @ 2022-03-03T10:09:08.911Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
background.js:77600  🪵 Tally log @ 2022-03-03T10:09:15.817Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
background.js:77600  🪵 Tally log @ 2022-03-03T10:09:29.075Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
background.js:77600  🪵 Tally log @ 2022-03-03T10:09:30.081Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
background.js:77600  🪵 Tally log @ 2022-03-03T10:09:30.245Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
background.js:77600  🪵 Tally log @ 2022-03-03T10:09:30.431Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
background.js:77600  🪵 Tally log @ 2022-03-03T10:09:31.266Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
background.js:77600  🪵 Tally log @ 2022-03-03T10:10:21.441Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
background.js:77600  ❌ Tally error @ 2022-03-03T10:11:00.145Z
background.js:77601 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77856:41
genericLogger @ background.js:77601
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
background.js:77600  🪵 Tally log @ 2022-03-03T10:11:50.271Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
background.js:77600  ❌ Tally error @ 2022-03-03T10:12:01.667Z
background.js:77601 Error getting block prices from BlockNative Error: failed response (requestBody=null, requestMethod="GET", url="https://api.blocknative.com/gasprices/blockprices", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at Logger.throwError (background.js:11671:22)
    at background.js:77964:37
    at Generator.next (<anonymous>)
    at fulfilled (background.js:77706:28)
genericLogger @ background.js:77601
background.js:77600  🪵 Tally log @ 2022-03-03T10:12:12.649Z
background.js:77601 error processing request Error: The Provider does not support the requested method.
    at InternalEthereumProviderService.routeSafeRPCRequest (background.js:91711:17)
    at ProviderBridgeService.routeContentScriptRPCRequest (background.js:91258:65)
    at ProviderBridgeService.onMessageListener (background.js:91132:40)
background.js:77609     at ProviderBridgeService.routeContentScriptRPCRequest (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91262:22)
    at async ProviderBridgeService.onMessageListener (chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js:91132:29)
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
DevTools failed to load source map: Could not load content for chrome-extension://jgefjegfelmgighcdihofpcnhgnlgamn/background.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
background.js:77600  ❌ Tally error @ 2022-03-03T10:15:00.149Z
background.js:77601 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:11662:25)
    at background.js:77856:41
genericLogger @ background.js:77601
error @ background.js:77627
getBlockPrices @ background.js:82990
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
background.js:77677          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ background.js:77677
(anonymous) @ background.js:77657
geturl_awaiter @ background.js:77639
getUrl @ background.js:77661
(anonymous) @ background.js:77882
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
fulfilled @ background.js:77706
Promise.then (async)
step @ background.js:77719
(anonymous) @ background.js:77721
web_lib_esm_awaiter @ background.js:77703
(anonymous) @ background.js:77878
_fetchData @ background.js:77970
lib_esm_fetchJson @ background.js:78010
getBlockPrices @ background.js:82965
getBlockPrices @ background.js:82988
(anonymous) @ background.js:88150
pollBlockPrices @ background.js:88149
handler @ background.js:87950
handleAlarm @ background.js:73994
```

**Comment by SJQuality** [comment]
@Naxsun I'm not even seeing Tally as an option :( 
![image](https://user-images.githubusercontent.com/103908695/167710760-bded04ad-6789-492d-bf80-b07e74357c0a.png)

**Comment by Naxsun** [comment]
This one is fixed actually :) For me at least.

Try when you have Tally Ho as your default wallet selecting 'Web3', 2nd one on the top

**Comment by SJQuality** [comment]
@Naxsun Ah, there it is. Thanks. And no problems. Closing.
