### ISSUE TITLE
Windows build is broken (037dac81c70a3395bda0e8384c06cfdac1c76646)

### ISSUE THREAD

**Issue by ElderOrb** [tallycash/extension#1379]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

yarn start

### What did not work?

<i> [LiveReloadPlugin] Live Reload listening on port 35729                                                                                                    Error: error:0308010C:digital envelope routines::unsupported                                                                                                      at new Hash (node:internal/crypto/hash:67:19)                                                                                                                 at Object.createHash (node:crypto:135:10)                                                                                                                     at BulkUpdateDecorator.hashFactory (D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\util\createHash.js:155:18)                                at BulkUpdateDecorator.update (D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\util\createHash.js:55:51)                                      at D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\DefinePlugin.js:568:16                                                                     at Array.forEach (<anonymous>)                                                                                                                                at walkDefinitionsForValues (D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\DefinePlugin.js:564:31)                                          at D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\DefinePlugin.js:591:5                                                                      at Hook.eval (eval at create (D:\Projects.local\.fun\tally\extension\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:100:1)                   at Hook.CALL_DELEGATE [as _call] (D:\Projects.local\.fun\tally\extension\node_modules\tapable\lib\Hook.js:14:14) {                                          opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],                                                                      library: 'digital envelope routines',                                                                                                                         reason: 'unsupported',                                                                                                                                        code: 'ERR_OSSL_EVP_UNSUPPORTED'                                                                                                                            }                                                                                                                                                             error Command failed with exit code 1.                                                                                                                        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                          ERROR: "dev" exited with 1.                                                                                                                                   error Command failed with exit code 1.                                                                                                                        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 

### Relevant log output

```shell
<i> [LiveReloadPlugin] Live Reload listening on port 35729                                                                                                    Error: error:0308010C:digital envelope routines::unsupported                                                                                                      at new Hash (node:internal/crypto/hash:67:19)                                                                                                                 at Object.createHash (node:crypto:135:10)                                                                                                                     at BulkUpdateDecorator.hashFactory (D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\util\createHash.js:155:18)                                at BulkUpdateDecorator.update (D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\util\createHash.js:55:51)                                      at D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\DefinePlugin.js:568:16                                                                     at Array.forEach (<anonymous>)                                                                                                                                at walkDefinitionsForValues (D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\DefinePlugin.js:564:31)                                          at D:\Projects.local\.fun\tally\extension\node_modules\webpack\lib\DefinePlugin.js:591:5                                                                      at Hook.eval (eval at create (D:\Projects.local\.fun\tally\extension\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:100:1)                   at Hook.CALL_DELEGATE [as _call] (D:\Projects.local\.fun\tally\extension\node_modules\tapable\lib\Hook.js:14:14) {                                          opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],                                                                      library: 'digital envelope routines',                                                                                                                         reason: 'unsupported',                                                                                                                                        code: 'ERR_OSSL_EVP_UNSUPPORTED'                                                                                                                            }                                                                                                                                                             error Command failed with exit code 1.                                                                                                                        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                          ERROR: "dev" exited with 1.                                                                                                                                   error Command failed with exit code 1.                                                                                                                        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ElderOrb** [comment]
The issue can be closed because it is unrelated to tally (nodej 18-specific). Switching to 16.0.0 did help.
