### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by PabloCastellano** [tallycash/extension#986]
### What browsers are you seeing the problem on?

Firefox, Chrome, Brave

### What were you trying to do?

I'm following the README in order to compile the extension for chromium.

I'm using Linux Mint (based on Ubuntu 20.04)

### What did not work?

I'm seeing the following output in my console, indicating that `@babel/helper-environment-visitor` can't be found.

```
  ERROR in ./src/window-provider.ts
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: [BABEL]: Cannot find module '@babel/helper-environment-visitor'
  Require stack:
  - /home/pablo/src/tally-extension/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/conversion.js
  - /home/pablo/src/tally-extension/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/index.js
  - /home/pablo/src/tally-extension/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js
  - /home/pablo/src/tally-extension/node_modules/@babel/core/node_modules/@babel/traverse/lib/traverse-node.js
  - /home/pablo/src/tally-extension/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js
  - /home/pablo/src/tally-extension/node_modules/@babel/core/lib/index.js
  - /home/pablo/src/tally-extension/node_modules/babel-loader/lib/index.js
  - /home/pablo/src/tally-extension/node_modules/loader-runner/lib/loadLoader.js
  - /home/pablo/src/tally-extension/node_modules/loader-runner/lib/LoaderRunner.js
  - /home/pablo/src/tally-extension/node_modules/webpack/lib/NormalModuleFactory.js
  - /home/pablo/src/tally-extension/node_modules/webpack/lib/Compiler.js
  - /home/pablo/src/tally-extension/node_modules/webpack/lib/webpack.js
  - /home/pablo/src/tally-extension/node_modules/webpack/lib/index.js
  - /home/pablo/src/tally-extension/node_modules/webpack-cli/lib/webpack-cli.js
  - /home/pablo/src/tally-extension/node_modules/webpack-cli/lib/bootstrap.js
  - /home/pablo/src/tally-extension/node_modules/webpack-cli/bin/cli.js
  - /home/pablo/src/tally-extension/node_modules/webpack/bin/webpack.js (While processing: /home/pablo/src/tally-extension/node_modules/@babel/preset-env/lib/index.js)
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
      at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/pablo/src/tally-extension/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (/home/pablo/src/tally-extension/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
      at Object.<anonymous> (/home/pablo/src/tally-extension/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/conversion.js:14:33)
      at Module._compile (/home/pablo/src/tally-extension/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Module.load (internal/modules/cjs/loader.js:950:32)
      at Function.Module._load (internal/modules/cjs/loader.js:790:12)

  chrome compiled with 6 errors
```

Unfortunately I have not been able to install it:

```
$ npm install @babel/helper-environment-visitor

npm ERR! Object for dependency "mockzilla-webextension" is empty.
npm ERR! Something went wrong. Regenerate the package-lock.json with "npm install".
npm ERR! If using a shrinkwrap, regenerate with "npm shrinkwrap".

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pablo/.npm/_logs/2022-02-12T21_52_51_650Z-debug.log
```

Now I'm stuck since none of these solutions work

**Comment by Shadowfiend** [comment]
You should be using `yarn` for all package management commands. Does that also fail? We have a continuous build running on Ubuntu so in general we expect it to work correctly.

**Comment by PabloCastellano** [comment]
Thanks! By reviewing the CI commands I was able to spot the problem. `nvm install` is required in addition to `nvm use`. I will update https://github.com/tallycash/extension/pull/988 to include this change :+1:

**Comment by Shadowfiend** [comment]
Awesome, thank you so much!
